# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.1
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: sarajanedeveloper@gmail.com
author_name: SaraJane
contract_name: clickr_logic
preset_name: production
project_name: Clickr_App_TS-contracts

